Dev greenie
TechLabs-Berlin/wt21-commfy pull request #5
Opened 2022-01-04 12:49 UTC by Flogreeni

Sorry to the reviewer, cause i deleted the rep on my computer it kind of looks like I just deleted the files and builded new ones. So it is really hard to see the differeneces between the older versions

2022-01-04 13:05 UTC, maximilian-hildebrandt approved these changes

2022-01-04 13:07 UTC, maximilian-hildebrandt approved these changes, later dismissed

2022-01-06 22:24 UTC, maximilian-hildebrandt requested changes
1 Rule-Based Model Notebook
General

- Please separate pull requests into standalone files, e.g. this time we had the rule-based model code, Flask API and readme in one pull request. I can more easily approve urgent changes (like Flask-related) if it is standalone. Create branches per feature that you modify and then create pull-requests for those smaller branches. 
- I approve the flask & readme part, the rule-based notebook needs some more work. Consequently, all files are not yet merged until the rule-based notebook is fixed.

- As mentioned in my previous feedback, check your notebook for spelling (e.g., capital letters in headings and comments, "gather" statt "gether", consistent usage of dots at the end of sentences). This would add to a positive perception of the results of your work, which otherwise are quite good. 

Structure

- Your section data exploration is missing, data cleaning does not contain any cleaning but further data collection.
- As mentioned in my previous feedback, data exploration of input data using summary statistics & visualizations? Pre-processing of data needed? If you collect wheather data, please create some exploratory data analyses (statistics, visuals) to check the plausibility of the fetched data.
- Model evaluation should come before concatenating output.

 
Wheather function

- The function is located in "Part 3 data cleaning", although this seems to be data collection. Move it into the previous section.
- Great to see the weather function work well. I like that you test the function and provide a sample output (also in a pandas dataframe ;)).
- You could comment out complex functions more, explaining in each row what you did. This make it easier for reviewers to follow and is a more reader-centric way of coding. For example for this line of code a short comment would have reduced my time to process it a lot:  if(abs((df_time-now).total_seconds())<abs((time_forecast-df_time).total_seconds()))&(abs((df_time-now).total_seconds())<abs((time_forecast2-df_time).total_seconds())):

Output concatenating

- Please comment your code so that it is easier to digest (after complex rows of code add a comment in the same line at the end #testcomment.

2 Flask API
General

- Functions of the API are useful, thanks, although you included a few functions which are not necessary (time that could be used for the core deliverables like the rule-based logic or code). 
- Do we need an input function for them to provide us with the user data? How can they submit their data?
- There is a minor spelling error (the clothes to wear on each trip of the input (inside…)

Structure

- The ordering could be modified from my point of view by ordering the functions by importance. The most important function for users is the recommendation output, so place it at the top. 
- Move all optional functions to a separate section "Optional - for testing purposes" (see all possible inputs, see all outfits, possible input json, random output")

2022-01-16 17:43 UTC, Flogreeni commented
Hi Max, I included a lot of your Feedback - I thing not holding back from pushing to main:

Data cleaning: I added in the notebook structure how I am willing to process the Datacleaning. It is not yet implemented.

Model Evaluation: I have a hard time to evaluate our model (here is missing some data in my opinion) we could just evaluate by asking the user if the prediction is correct. (and still then it is just comparing to a feeling of a user before commuting and also not really evaluating the model)

the Output concatenating is now much better and gives way better output for the backpack.

Flask_API the spelling error is removed.
I would not like to change the structure of the API without telling the WD track, cause I thing they already use the API.
So I get your point in changing the API´s structure into relevant and testing purposes, if necessary will change it after next meeting with the WD track so I can tell them.

they can already provide us with input data. When they use".../api/recommendation" they can give in the body a json and the recommendation will be to there input.

2022-01-21 21:14 UTC, merged